name = "TerminalSpinners"
uuid = "30eb84dd-517b-496a-98ca-bc270c08ac37"
authors = ["KristofferC <kcarlsson89@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
